Updated the fast_network script to run even if docker is not started.

diff --git a/docker/controller/install/postscrips/fast_network b/docker/controller/install/postscrips/fast_network
--- a/docker/controller/install/postscrips/fast_network
+++ b/docker/controller/install/postscrips/fast_network
@@ -20,14 +20,14 @@ if [ -z "$IP" ]; then
    exit 1
 fi
 
-#if ! ifconfig docker0 > /dev/null 2>&1; then
-#   echo "Interface docker0 not found. Please start docker first."
-#   exit 1
-#fi
-
-#GW=$(ip addr show dev docker0 scope global | grep inet | awk -F' ' '{print $2}')
+if ! ifconfig docker0 > /dev/null 2>&1; then
+   echo "Interface docker0 not found. Please start docker first."
+   #service docker start
+   #sleep 3
+fi
 
 brctl addbr docker0
+ip link set docker0 up
 
 IP3_4=$(echo $IP | awk -F'/' '{print $1}' | awk -F'.' '{print $3"."$4}')
 IP3_4_GW=$(echo $IP | awk -F'/' '{print $1}' | awk -F'.' '{print $3+127"."$4}')
@@ -35,7 +35,7 @@ IP3_4_GW=$(echo $IP | awk -F'/' '{print $1}' | awk -F'.' '{print $3+127"."$4}')
 # setup two interfaces docker0 with the gateway interface and docker0:0 in the bridge
 ip addr flush dev docker0
 ip addr add 172.17.${IP3_4_GW}/16 dev docker0
-ip addr add ${IP}/16 dev docker0
+ip addr add ${IP} dev docker0
 
 # remove the ip addres from eth0
 ip addr flush dev eth0
